[build]
  publish = "."

[[redirects]]
  from = "/tt"
  to = "/?utm_source=tiktok&utm_medium=social"
  status = 301
  force = true

[[redirects]]
  from = "/ig"
  to = "/?utm_source=instagram&utm_medium=social"
  status = 301
  force = true

[[redirects]]
  from = "/th"
  to = "/?utm_source=threads&utm_medium=social"
  status = 301
  force = true
